### ISSUE TITLE
Échantillon, nombre de pages et pages obligatoires

### ISSUE THREAD

**Issue by sebastiendelorme** [DISIC/guide-auditeur#1]
Bonjour,

Le guide de l'auditeur précise : "L’échantillon possède-t-il 15 pages, au moins ?".

Bien qu'il soit précisé que "ce document est purement informatif", cette phrase entre en contradiction avec le [guide d'accompagnement du RGAA](http://references.modernisation.gouv.fr/rgaa-accessibilite/guide-accompagnement-RGAA.html) (document officiel) qui, lui, précise : 
- "La taille de cet échantillon peut varier suivant le nombre de pages, les contenus proposés, le nombre de formulaires, les processus transactionnels, etc…"
- "À titre indicatif, l’échantillon standard comprend généralement une quinzaine de pages.".

Le volume de pages n'est donc pas nécessairement de 15 pages.
Est-il possible de reprendre une formulation similaire à celle du guide d'accompagnement, pour éviter les confusions sur le volume de pages ?

De plus, les pages obligatoires mentionnées dans le guide de l'auditeur sont (en dehors bien sûr de celles sélectionnées pour leurs contenus - tableaux, multimédia, etc.) : 
- Accueil
- Plan du site
- Recherche
- Aide
- Déclaration de conformité au RGAA

Là où le guide d'accompagnement du RGAA liste en plus les deux pages suivantes : 
- Contact
- Mentions légales

De la même façon, ne serait-il pas intéressant d'harmoniser cette liste ?

**Comment by Etat-Plateforme** [comment]
Merci pour vos remarques.

Il est spécifié dans les paragraphes suivants qu'effectivement l'échantillon peut-être de moins de 15 pages selon les contextes (eux-mêmes détaillés).  Nous avons tout de même ajouté la mention « si nécessaire » pour moduler ce nombre de 15 pages : « L'échantillon est-il composé, si nécessaire, de 15 pages, au moins ? ». Cette formulation répond-elle bien à votre demande d'harmonisation ?

Concernant la remarque sur les pages obligatoires, nous avons bien pris en compte vos suggestions et avons revu cette liste pour être au plus près du guide d'accompagnement.

**Comment by sebastiendelorme** [comment]
Bonjour,

Merci pour la prise en compte de ces remarques.

Bien à vous,
Sébastien Delorme
